# Generated by Django 5.1.6 on 2025-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate')], max_length=100, null=True),
        ),
    ]
