# Generated by Django 5.1.6 on 2025-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicaluser_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='department',
            field=models.CharField(blank=True, choices=[('Route Complete Cargo', 'RCC'), ('Air-Sea Cargo', 'ASR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Route Complete Cargo', 'RCC'), ('Air-Sea Cargo', 'ASR')], max_length=100),
        ),
    ]
