# Generated by Django 5.1.6 on 2025-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluser_createdobjects_user_createdobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate'), ('Viewer', 'Viewer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate'), ('Viewer', 'Viewer')], max_length=100, null=True),
        ),
    ]
