# Generated by Django 5.1.6 on 2025-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_historicaluser_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='department',
            field=models.CharField(blank=True, choices=[('Route Complete Cargo', 'RCC'), ('Air-Sea Cargo', 'ASR'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate'), ('Viewer', 'Viewer'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Route Complete Cargo', 'RCC'), ('Air-Sea Cargo', 'ASR'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Subordinate', 'Subordinate'), ('Viewer', 'Viewer'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
    ]
